### PR TITLE
Updates Pull Request Template

### LINKED ISSUE #451: Add `I have squashed my commits` to the PRs template checklist
Add `I have squashed my commits` to the [PRs template checklist](https://github.com/scanapi/scanapi/blob/main/.github/pull_request_template.md#checklist). Also, add to the message a link to the wiki page where we explain how to do it (#450 )

### PR DESCRIPTION
**Pull request by renato04**
Updates Pull Request Template with `I have squashed my commits` item in the checklist

Closes #451
## Checklist
 

- [x]  I have added a changelog entry / my PR does not need a new changelog entry. [Instructions](https://github.com/scanapi/scanapi/wiki/Changelog).
- [ ] I have added/updated unit tests. [Instructions](https://github.com/scanapi/scanapi/wiki/Writing-Tests).
- [ ] New and existing unit tests pass locally with my changes. [Instructions](https://github.com/scanapi/scanapi/wiki/Run-ScanAPI-Locally#tests)
- [ ] I have self-documented code my changes by adding docstring(s) and comment(s). [Instructions](https://github.com/scanapi/scanapi/wiki/First-Pull-Request#7-make-your-changes)
- [x] Current PR does not significantly decrease the code coverage and docstring coverage.
- [ ] My code follows the style guidelines of this project.
- [ ] I have run ScanAPI locally and manually tested my changes. [Instructions](https://github.com/scanapi/scanapi/wiki/Run-ScanAPI-Locally).

### CODE REVIEW

**Comment by renato04** [comment]
Hi @scanapi/maintainers!
What is this changelog that the bot said is missing?

**Comment by marcorichetta** [comment]
> What is this changelog that the bot said is missing?

Hi @renato04! It's automatically ran on every PR.

In this case, you can check the option _I have added a changelog entry / my PR does not need a new changelog entry._ because your changes do not need a changelog, I believe.

**Review by camilamaia — APPROVED** [review]
@renato04 thank you very much for the PR and for the wiki page!! It sounds great to me. I'd love to also hear your thoughts, @Pradhvan since you are the squash expert :)

**Comment by Pradhvan** [comment]
This is really great. Thank you for the PR @renato04 ⭐

**Pull request merged**
