### PR TITLE
Adjusting `make install`

### LINKED ISSUE #683: `make install` instruction does not work
### Environment
- Python version: 3.13.0
- Poetry version: 1.8.3

### Description of the bug 

When trying to install scanapi locally, as in the [wiki](https://github.com/scanapi/scanapi/wiki/Run-ScanAPI-Locally#install), with the `make install` command an error is raised saying the `poetry.lock` file is out of date with respect to the `pyproject.toml` dependencies.

```sh
Installing dependencies from lock file

pyproject.toml changed significantly since poetry.lock was last generated. Run `poetry lock [--no-update]` to fix the lock file.
```

### Expected behavior ?

The dependencies should be installed as described in the wiki.

### How to reproduce the the bug ?

Run the command `make install`

### Anthing else we need to know?

The error already indicates the solution: `poetry lock --no-update`

### PR DESCRIPTION
**Pull request by taconi**
## Description

Adjusting `make install`

## Motivation behind this PR?

releated #683 

## What type of change is this?

Bug Fix

## Checklist
 

- [X]  I have added a changelog entry / my PR does not need a new changelog entry. [Instructions](https://github.com/scanapi/scanapi/wiki/Changelog).
- [ ] I have added/updated unit tests. [Instructions](https://github.com/scanapi/scanapi/wiki/Writing-Tests).
- [ ] New and existing unit tests pass locally with my changes. [Instructions](https://github.com/scanapi/scanapi/wiki/Run-ScanAPI-Locally#tests)
- [ ] I have self-documented code my changes by adding docstring(s) and comment(s). [Instructions](https://github.com/scanapi/scanapi/wiki/First-Pull-Request#7-make-your-changes)
- [X] Current PR does not significantly decrease the code coverage and docstring coverage.
- [ ] My code follows the style guidelines of this project.
- [X] I have run ScanAPI locally and manually tested my changes. [Instructions](https://github.com/scanapi/scanapi/wiki/Run-ScanAPI-Locally).
- [X] I have squashed my commits. [Instructions](https://github.com/scanapi/scanapi/wiki/Squashing-Commits).

## Issue

Closes #683

### CODE REVIEW

**Comment by taconi** [comment]
I don't understand if the error in the CI publishing the code coverage is related to my change:

```sh
[2024-10-11T16:49:08.866Z] ['error'] There was an error running the uploader: Error uploading to [https://codecov.io:](https://codecov.io/) Error: There was an error fetching the storage URL during POST: 429 - {"message":"Rate limit reached. Please upload with the Codecov repository upload token to resolve issue. Expected time to availability: 1612s."}
```

**Comment by camilamaia** [comment]
@taconi I've updated the codecov token. It should work now 🤞

**Comment by taconi** [comment]
lock updated in #685, but the pre-commit install command fails because it only exists inside venv

**Review by camilamaia — APPROVED** [review]
Nice!! Thanks! I'll fix the Codecov so it doesn't need a token since the repo is public. I think it's trying to get the token from the fork.

**Pull request merged**
