### PR TITLE
feat: After the process run print a test summary in console

### LINKED ISSUE #497: Show test result summary in the console
### Description the feature
Show the test result summary in the console and return a status process error.
The objective is if I put the Scan API on a pipeline this pipeline has to be stopped if there is an error. 

### Is your feature request related to a problem?
No.

### Do you have any suggestions on how to add this feature in scanapi ?
No.

### PR DESCRIPTION
**Pull request by renato04**
## Description
After running all process show a summary result in console

## Motivation behind this PR?
it resolves  #497

## What type of change is this?
Feature

## Checklist
 

- [x]  I have added a changelog entry / my PR does not need a new changelog entry. [Instructions](https://github.com/scanapi/scanapi/wiki/Changelog).
- [x] I have added/updated unit tests. [Instructions](https://github.com/scanapi/scanapi/wiki/Writing-Tests).
- [x] New and existing unit tests pass locally with my changes. [Instructions](https://github.com/scanapi/scanapi/wiki/Run-ScanAPI-Locally#tests)
- [x] I have self-documented code my changes by adding docstring(s) and comment(s). [Instructions](https://github.com/scanapi/scanapi/wiki/First-Pull-Request#7-make-your-changes)
- [ ] Current PR does not significantly decrease the code coverage and docstring coverage.
- [x] My code follows the style guidelines of this project.
- [x] I have run ScanAPI locally and manually tested my changes. [Instructions](https://github.com/scanapi/scanapi/wiki/Run-ScanAPI-Locally).
- [X] I have squashed my commits. [Instructions](https://github.com/scanapi/scanapi/wiki/Squashing-Commits).

## Issue
Closes #497

### CODE REVIEW

**Comment by Pradhvan** [comment]
@renato04 hey 👋🏾  Thank You for the PR. 

Can you use [rich](https://pypi.org/project/rich/) for showing to summary in the console ?  If we use `rich` it would give a lot of features that we can further use as scanapi matures. 

Let me know what you think. 😄

**Comment by renato04** [comment]
@Pradhvan that is a good idea.
But I can't change it right now.
Could you accept as is right now? And after I'll change to use rich

**Comment by Pradhvan** [comment]
@renato04 hey! can you add rich on this PR change only ? An iteration would be a bit longer process. 😄

**Comment by astenstrasser** [comment]
Hey @renato04, I added your commit to the PR #542, so I could rebase with main branch and add rich.

**Pull request closed without merging**
