### PR TITLE
Updates README file with the new demo api version

### LINKED ISSUE #368: Update README with new Demo API
## Description

We need to update the examples in the README.md file that uses demo.scanapi.dev/api/. We've [changed the API](https://github.com/scanapi/demo-api/issues/16) and the doc should reflect that.

Old API: https://demo.scanapi.dev/api/
New API: https://demo.scanapi.dev/

### PR DESCRIPTION
**Pull request by renato04**
* changing the image files for the new api
* updating the README images links

Closes #368

## Checklist
 

- [ ]  I have added a changelog entry / my PR does not need a new changelog entry. [Instructions](https://github.com/scanapi/scanapi/wiki/Changelog).
- [ ] I have added/updated unit tests. [Instructions](https://github.com/scanapi/scanapi/wiki/Writing-Tests).
- [ ] New and existing unit tests pass locally with my changes. [Instructions](https://github.com/scanapi/scanapi/wiki/Run-ScanAPI-Locally#tests)
- [ ] I have self-documented code my changes by adding docstring(s) and comment(s). [Instructions](https://github.com/scanapi/scanapi/wiki/First-Pull-Request#7-make-your-changes)
- [x] Current PR does not significantly decrease the code coverage and docstring coverage.
- [ ] My code follows the style guidelines of this project.
- [ ] I have run ScanAPI locally and manually tested my changes. [Instructions](https://github.com/scanapi/scanapi/wiki/Run-ScanAPI-Locally).

### CODE REVIEW

**Comment by renato04** [comment]
@Pradhvan @camilamaia 
After the tip to squash the commits into one commit, I open another pull request.

**Comment by hebertjulio** [comment]
@renato04 thank you for your contribution, :smile: 

You forgot update CHANGELOG.md file. After you update it, you can do a commit amend to update your last commit.

**Comment by Pradhvan** [comment]
@hebertjulio for updating docs I don't think we need to add a changelog entry.  @camilamaia what do you think ?

**Comment by camilamaia** [comment]
@Pradhvan @hebertjulio there is no need for a new entry here :)

https://github.com/scanapi/scanapi/wiki/Changelog#what-warrants-a-changelog-entry

> Any docs-only changes should not have a changelog entry.

Can I merge the PR?

**Review by camilamaia — APPROVED** [review]
💯

**Comment by camilamaia** [comment]
@renato04 Congrats for your first PR merged! Thank you very much!

I am going to send you an invite to join the ScanAPI org on GitHub 🚀 We invite everyone that has contributed with a merged PR in any of our repos. Here you can check our [Contributing Guidelines](https://github.com/scanapi/contributors/blob/main/CONTRIBUTING.md) so you can understand better how it works.

And once again, thank you! 🙇‍♀️

**Pull request merged**
