### PR TITLE
New Html template

### LINKED ISSUE #61: Make html report pretty
💄 

- [ ] Show only path_url in the titles
- [ ] Add response and request headers
- [ ] Add request headers and body
- [ ] Add response headers, metada and body
- [ ] Add cURL
- [ ] Add response time

### PR DESCRIPTION
**Pull request by djalmaaraujo**
New HTML template using jinja. 🥳 

- Assets uploaded to S3 (@camilamaia)

The reason the CSS is inline is because we want to avoid adding useless dependencies to the project.

image

Closes #61 https://github.com/scanapi/scanapi/issues/57

### CODE REVIEW

**Comment by camilamaia** [comment]
image

image

**Comment by camilamaia** [comment]
> This is looking good.
> 
> Something that comes to my mind now is that if these green/yellow/red colors may give the impression of success/failure for each of the requests being executed.

Good point. We will bring tests results to this report soon. So we will display in a clear way if the test pass or failed. Maybe a big `check` or `x` before the http method. Or the border of each row in green if passed, or red if not. We need to think more about it.

But I believe, then, we will not have this confusion. What do you think?

**Comment by camilamaia** [comment]
Also, you can check an example of the generated report here: https://github.com/scanapi/scanapi-examples/blob/master/scanapi-demo/scanapi-report.html

**Comment by barbosa** [comment]
Yeah, that's something to think about. Especially if we plan to bring test results to the same report.

Red to me looks like something errored.

**Comment by camilamaia** [comment]
> Yeah, that's something to think about. Especially if we plan to bring test results to the same report.
> 
> Red to me looks like something errored.

I can create a new "ARD" to discuss about the tests results in the reports (both html and md)

**Comment by camilamaia** [comment]
@barbosa https://github.com/scanapi/scanapi/issues/161

**Pull request merged**
