### PR TITLE
Use Python3 simple super call (close #455)

### LINKED ISSUE #455: Possibly broken super() call
### Environment
LGTM analysis

### Description of the bug 
First argument to super() is not enclosing class
→ https://lgtm.com/projects/g/scanapi/scanapi/snapshot/975eee8439217318dce6c39d70c1d700d6f33bd6/files/scanapi/settings.py?sort=name&dir=ASC&mode=heatmap#xb5202bf2b059205b:1

### Expected behavior?
Rewrite this to just `super()...`.

### PR DESCRIPTION
**Pull request by jhermann**
Change from (wrong) Py2 super() call to the simple Py3 form.
Also changing *all* super calls to the simpler form.
Local tests pass.

closes #455

### CODE REVIEW

**Review by hebertjulio — APPROVED** [review]
Thank you very much for the contribution! :smile:

**Comment by jhermann** [comment]
Ready for merge.

**Comment by hebertjulio** [comment]
Thanks @jhermann , great job! :smile:

There are two points that need to be fixed.

Point 1: make squash with yours commit, creating one commit.
Point 2: resolve deepsource issues. [analysis history here](https://deepsource.io/gh/scanapi/scanapi/run/24bfbd64-e7cf-440f-a406-e7146803b924/python/)

**Comment by jhermann** [comment]
2 - that was pre-existing. many of your doc strings are missing "end the 1st sentence with a dot", btw.
1 - please use GitHub's "squash" option on merge -- **way** easier than applying some CLI git voodoo

**Comment by hebertjulio** [comment]
@camilamaia look good to me.

**Pull request merged**
