### PR TITLE
make change-version: create a readable PEP440-compatible dev version

### PR DESCRIPTION
**Pull request by jhermann**
Make "make change-version" useful again by keeping the current release version, and adding a human readable and PEP440 compliant timestamp to it.

Also fixed `PHONY`.

Closes https://github.com/scanapi/scanapi/issues/464

### CODE REVIEW

**Comment by camilamaia** [comment]
Hey @jhermann, thank you very much for the contribution! 

Would you mind creating an [issue](https://github.com/scanapi/scanapi/issues) for this problem? We try to have an issue before we open the PR, this way we can discuss if the change makes sense.

But your suggestion is really a good one, thanks for it!

I tried to run it here and this is what I am getting:

```shell
workspace/scanapi-org/scanapi  fix-change-version ✗                                                     1h1m ◒
▶ make change-version
date: illegal option -- -
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
Bumping version from 2.5.0 to 2.5.0.dev
(scanapi-KvDFA3Cq-py3.6)
workspace/scanapi-org/scanapi  fix-change-version ✗                                                   1h1m ⚑ ◒
▶ make change-version
date: illegal option -- -
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
Bumping version from 2.5.0.dev to 2.5.0.dev.dev
(scanapi-KvDFA3Cq-py3.6)
workspace/scanapi-org/scanapi  fix-change-version ✗                                                   1h2m ⚑ ◒
▶ make change-version
date: illegal option -- -
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
Bumping version from 2.5.0.dev.dev to 2.5.0.dev
```

Is seems the timestamp is not working 🤔 Are you having a different output there?

**Comment by jhermann** [comment]
Ubuntu 18.04 (WSL1), it might be a Posix issue. What are you on, a Mac?

**Comment by jhermann** [comment]
And this is the output from release version to dev to updated dev:

```
Bumping version from 2.5.0 to 2.5.0.dev2021.07.31.171944
Bumping version from 2.5.0.dev2021.07.31.171944 to 2.5.0.dev2021.07.31.171947
```

I simplified the shell calls, try again.

**Comment by camilamaia** [comment]
Yep! I am using Mac. It works now 🎉🎉 Also, I've created the issue for it: https://github.com/scanapi/scanapi/issues/464

**Review by camilamaia — APPROVED** [review]

**Comment by camilamaia** [comment]
@jhermann Congrats for your first PR merged! Thank you very much!

I am going to send you an invite to join the ScanAPI org on GitHub 🚀 We invite everyone that has contributed with a merged PR in any of our repos. Here you can check our [Contributing Guidelines](https://github.com/scanapi/contributors/blob/main/CONTRIBUTING.md) so you can understand better how it works.

And once again, thank you! 🙇‍♀️

**Pull request merged**
