### PR TITLE
Allow ${{}} exprs to call methods from external python modules

### PR DESCRIPTION
**Pull request by Zebralt**
#301

This PR adds the evaluator `RemoteMethodCallEvaluator`, It extends `CodeEvaluator` by allowing a RMC expression `<module>:≤python function call>` to be inserted in `${{}}` expressions, which so far only accepts pure Python code.

### RMC expression

A RMC expr allows you to invoke a method/function from a given python module:

```js
${{ std:response.ok }}
```
The right member of the expression must either be a a raw name as above or a typical Python call:
```js
std:response.status_is(200)
std:response.status_is(code=300, detail='jon')
```

### std

In addition to any module name, the left member also accepts two values: the empty string and `std`. Those two values means the module to import from is `scanapi/std.py`. `std.py` is meant to be a standard library of methods shipped with scanapi.

For now, `std` is only a module, but maybe it should become a package instead to avoid putting everything into a single file.

### How modules are imported

Modules are imported at evaluation time. Path resolution works the same as a regular import , i.e to import a local module you'll need to have it in your current working directory.

### How functions are called

The function is imported from its module, then
* if args/kwargs were provided in the right member of the RMC expr, they are bound to the function using `functools.partial`;
* the RMC evaluator attempts to feed `vars` to the function as efficiently as possible [here](https://github.com/Zebralt/scanapi/blob/master/scanapi/evaluators/rmc_evaluator.py#L44), in the following order:
  * if the function's spec can be inspected, the evaluator tries to see which names the function expects and feeds it only these, e.g. 
```py
vars = {'response': ResponseObject(), 'ids': [...]}
def response_ok(response):
    return response.status == 200
call_against_vars(f, (), {}, vars)  # will only send vars['response'] to response_ok
```
  * if there is no key in the spec that can be correlated with `vars`'s keys, an exception is raised.
  * if the spec cannot be inspected (such is the case of builtins), `vars` is fed as a single positional argument to the function.
  * if the spec has a `vars` argument, `vars` is fed as a keyword argument under that name.

---

#301 suggested that `vars` be fed implicitly to the function, but there may be a case for doing it explicitly instead; the right member is parsed using the ast module, and we could use it to parse name arguments as well; that wouldn't be too much of a stretch:
```py
${{ std:response_ok(response) }}  # search for 'response' name in vars
```

### CODE REVIEW

**Comment by Zebralt** [comment]
Weird, my local black setup gives a complete different result ...
```
reformatted scanapi\scanapi\__main__.py
reformatted scanapi\scanapi\hide_utils.py
reformatted scanapi\scanapi\reporter.py
would reformat scanapi\scanapi\scan.py
would reformat scanapi\scanapi\settings.py
would reformat scanapi\scanapi\utils.py
would reformat scanapi\scanapi\tree\request_node.py
```

**Comment by hebertjulio** [comment]
Hey @camilamaia 

This month i will take a vacation, and after i can work at this PR if necessary.

**Comment by camilamaia** [comment]
@hebertjulio perfect! It would help a lot. Have a great vacation!

**Comment by hebertjulio** [comment]
> @hebertjulio perfect! It would help a lot. Have a great vacation!

But I can take smalls issue. I can config black at pre-commit hook. What do you think?

**Comment by camilamaia** [comment]
Sorry, closing this PR for now since there was no recent activity 🧹  If you want to update it, feel free to reopen it.

**Pull request closed without merging**
