### PR TITLE
Upgrade pytest version to 6.1.0

### PR DESCRIPTION
**Pull request by kelvins**
- Context: the `pytest` settings moved from `pytest.ini` to `pyproject.toml` in the PR https://github.com/scanapi/scanapi/pull/283 are not actually being used because we are using an older `pytest` version which doesn't support `pyproject` (by running `make test` you can see the verbose mode is not activated).
- This PR fix it by upgrading `pytest` to version `6.1.0`.
- Related to the issue https://github.com/scanapi/scanapi/issues/276.

### CODE REVIEW

**Review by camilamaia — APPROVED** [review]
Great catch! I did not realise it, thanks!

Would you mind just to update your branch from the master? So I can merge?

Thank you!

**Comment by camilamaia** [comment]
@dbzkunalss look, the github action you implemented is working ⬆️ 👏 Awesome!

**Comment by dbzkunalss** [comment]
Woah, so cool!🙌

**Comment by kelvins** [comment]
@camilamaia sorry for the delay. Done :heavy_check_mark:

**Comment by camilamaia** [comment]
Hey, @kelvins thank you very much for the PR!

Also, as I said to the others, I am going to send you an invite to join the ScanAPI org on GitHub 🚀 We invite everyone that has contributed with a merged PR in any of our repos. Here you can check our [Community Continuity Guidelines](https://github.com/scanapi/contributors/blob/master/Contributing.md) so you can understand better how it works.

And once again, thank you! 🙇‍♀️

**Pull request merged**
