### PR TITLE
automation: add autoenv '.env' activator for poetry venv

### PR DESCRIPTION
**Pull request by jhermann**
As discussed on EP matrix channel, activate the venv on (auto-)cd into the project workdir.

@camilamaia please check if this works on MacOS (the readlink -f might fail).

### CODE REVIEW

**Comment by Stannislav** [comment]
Hi Jürgen, just wondering, isn't it bad practise to check in the `.env` file? I'm more used to seeing it in `.gitignore`. I know people use it to save API keys and other secrets.

And a totally different question - does your shell source the `.env` files automatically? Because otherwise you still need to type `source .env`.

**Comment by jhermann** [comment]
@Stannislav this .env is special, and I use autoenv for the "convenient" part.

→ [Simplify Your Developer Life with autoenv | Snakes on Callisto](https://jhermann.github.io/blog/tools/automation/2020/02/27/autoenv.html)

**Comment by Stannislav** [comment]
@jhermann, thanks, looks like an interesting tool.

I looked into the [autoenv repo](https://github.com/inishchith/autoenv) and they suggest using [direnv](https://direnv.net/) instead. Personally I do prefer direnv's recommended `.envrc` file over `.env` for the reasons I mentioned above. But whatever you guys decide, just wanted to add my two cents :)

**Comment by jhermann** [comment]
I need to switch at some time, but all those little busy-todos stack up.

**Comment by camilamaia** [comment]
@jhermann thanks for the PR! 

@marcuxyz can you give us some help here reviewing this PR? I honestly don't know if this is a good practice or not.

**Comment by hebertjulio** [comment]
Sorry @camilamaia but I don't know about that subject. but if you want to talk about it, I'll be happy. :cry:

**Comment by astenstrasser** [comment]
Hey, since we haven't reached a decision in favour of this and it is not solving any current issue, I will close this PR for now.

**Pull request closed without merging**
