### PR TITLE
Change default template to html

### LINKED ISSUE #159: Change HTML report to default
Change HTML report to default. Current it is markdown, but HTML is way more popular and our html report is [beautiful](https://github.com/scanapi/scanapi/pull/157) now

Here is where we need to change it: https://github.com/scanapi/scanapi/blob/master/scanapi/settings.py#L11

### PR DESCRIPTION
**Pull request by camilamaia**
Change default template to html. Closes #159

### CODE REVIEW

**Comment by camilamaia** [comment]
> You may also want to add HTML as the default option on `__init__.py`

@barbosa I believe we cannot do that. If reporter is set as `markdown` in the config file and not via console, we would overwrite it with `html` anyway.

**Comment by barbosa** [comment]
@camilamaia Hmm I see. So maybe we have a design issue here? Some arguments have their default value set via `click` and others via `Settings`, is that it?

**Comment by camilamaia** [comment]
@barbosa maybe... we have a priority here:

1st: options from click
2nd: options from config path

https://github.com/scanapi/scanapi/blob/master/scanapi/settings.py#L40-L41

Talking with examples: If i set `key x` in the config file as `1`, and i set the same `key x` via console as `2`, the program should consider the console more important and set `key x` as `2`

That is why we cannot use the default values from click. Do you see this as a problem? Can you think in a different way to do that? Thanks!

**Comment by camilamaia** [comment]
@barbosa I will merge this, but let's keep discussing it here, ok? If we think something needs to be done, I can create a new issue for it.

**Pull request merged**
