### PR TITLE
Fix anti-pattern issues

### LINKED ISSUE #403: Fix anti pattern issues mentioned in static analysis
### Description of the feature

To increase the quality of the project we are using static analysis to find out anti-patterns in the project. 

A detailed list of the issues can be found [here](https://deepsource.io/gh/scanapi/scanapi/issues/?category=antipattern)

💡 The Issue requires multiple PRs so more than one person can contribute to the issue.

### PR DESCRIPTION
**Pull request by sleao**
## Description
Fixed two anti-pattern issues from #403 

## Motivation behind this PR?
Because Deepsource said so, I guess

## What type of change is this?
Couple of lines, simple stuff

## Checklist

- [ ]  I have added a changelog entry / my PR does not need a new changelog entry. [Instructions](https://github.com/scanapi/scanapi/wiki/Changelog).
- [ ] I have added/updated unit tests. [Instructions](https://github.com/scanapi/scanapi/wiki/Writing-Tests).
- [x] New and existing unit tests pass locally with my changes. [Instructions](https://github.com/scanapi/scanapi/wiki/Run-ScanAPI-Locally#tests)
- [ ] I have self-documented code my changes by adding docstring(s) and comment(s). [Instructions](https://github.com/scanapi/scanapi/wiki/First-Pull-Request#7-make-your-changes)
- [x] Current PR does not significantly decrease the code coverage and docstring coverage.
- [ ] My code follows the style guidelines of this project.
- [ ] I have run ScanAPI locally and manually tested my changes. [Instructions](https://github.com/scanapi/scanapi/wiki/Run-ScanAPI-Locally).

## Issue
Doesn't close #403, but checks off two changes of the list.

### CODE REVIEW

**Comment by marcuxyz** [comment]
thanks :)

**Comment by camilamaia** [comment]
Hey @sleao, thanks for your contribution! Your PR seems great for me. 💯

But there is a weird thing happening. Deepsource is failing (not yours fault, probably some misconfiguration on our side):

image

but the new issue introduced is not in the modified lines:

image

The current configuration should prevent it:

image

@Pradhvan do you have any clue of what is going on here?

IMO, we can merge the PR and check the settings in parallel

**Review by camilamaia — APPROVED** [review]

**Comment by sleao** [comment]
Glad to help, @camilamaia! There's other stuff to change according to the Deepsource report but I was afraid of changing the structure of the code and break something big.

**Review by Pradhvan — CHANGES_REQUESTED** [review]
Hi! @sleao The changes look good. 👍🏾 

Just a few minor changes:

1) Can you add a docstring to the class `class Reporter:` that would fix the [deepsource](https://deepsource.io/gh/scanapi/scanapi/run/abd632a7-8dac-4624-a963-d2c80fd8ad8e/python/PY-D0002) check in the CI. You add a doc string to the class in a similar manner mentioned [here](https://github.com/scanapi/scanapi/wiki/First-Pull-Request#7-make-your-changes). 

2) Once done with the changes can you squash the commits into one and add a structured commit message associated with it. Since the PR is a refactor and won't require multiple commits. So squashing them into one would be good. 

You can follow the below commit template:

```
title of the commit

<body of the commit>
* replace if else boolean check with bool function
* removed redundant elif to if statement

Closes #<issue number>
```

**Comment by sleao** [comment]
Sure thing @Pradhvan. I think I squashed them but now it says I made 4 commits? I'm kinda lost right now, would love some help.

**Comment by Pradhvan** [comment]
@sleao what steps did you use to squash the commits into one ? Can you please tell me that, it would be really helpful. 

Also if you want to pair program on this, you can ping me on the [discord server](https://discord.com/invite/f3cCXJ2ZPB). You can share screen and we can work it out together.

**Review by camilamaia — APPROVED** [review]

**Comment by camilamaia** [comment]
@sleao can you just fix the DeepSource problems: https://deepsource.io/gh/scanapi/scanapi/run/f7823c98-2346-47d3-89e9-b1ce8d4f6059/python/ ?

I can squash it here for you then! Next time we will have a proper doc to guide you.

**Comment by camilamaia** [comment]
Closes #439
Closes #440

**Comment by sleao** [comment]
It should be good now, I think, after a few commits... that was harder than I expected. Thank you guys for all the help :)

**Review by camilamaia — APPROVED** [review]

**Comment by camilamaia** [comment]
@sleao thank YOU for the patience and for the hard work!

Also, congrats for your first PR merged! Thank you very much!

I am going to send you an invite to join the ScanAPI org on GitHub 🚀 We invite everyone that has contributed with a merged PR in any of our repos. Here you can check our [Contributing Guidelines](https://github.com/scanapi/contributors/blob/main/CONTRIBUTING.md) so you can understand better how it works.

And once again, thank you! 🙇‍♀️

**Pull request merged**
