### PR TITLE
Update the README file with the new demo api version

### LINKED ISSUE #368: Update README with new Demo API
## Description

We need to update the examples in the README.md file that uses demo.scanapi.dev/api/. We've [changed the API](https://github.com/scanapi/demo-api/issues/16) and the doc should reflect that.

Old API: https://demo.scanapi.dev/api/
New API: https://demo.scanapi.dev/

### PR DESCRIPTION
**Pull request by renato04**
## Description
Update the sample yaml file
## Checklist
 

- [ ]  I have added a changelog entry / my PR does not need a new changelog entry. [Instructions](https://github.com/scanapi/scanapi/wiki/Changelog).
- [ ] I have added/updated unit tests. [Instructions](https://github.com/scanapi/scanapi/wiki/Writing-Tests).
- [ ] New and existing unit tests pass locally with my changes. [Instructions](https://github.com/scanapi/scanapi/wiki/Run-ScanAPI-Locally#tests)
- [ ] I have self-documented code my changes by adding docstring(s) and comment(s). [Instructions](https://github.com/scanapi/scanapi/wiki/First-Pull-Request#7-make-your-changes)
- [x] Current PR does not significantly decrease the code coverage and docstring coverage.
- [ ] My code follows the style guidelines of this project.
- [ ] I have run ScanAPI locally and manually tested my changes. [Instructions](https://github.com/scanapi/scanapi/wiki/Run-ScanAPI-Locally).

## Issue

Closes #368

### CODE REVIEW

**Review by camilamaia — COMMENTED** [review]
Hey @renato04, thank you very much for your contribution!

Just one more thing, can we have the screenshots also updated to match the new demo-api version?

They are on README.md from line 77 to 93:

```
<p align="center">
  <img
    src="https://raw.githubusercontent.com/scanapi/scanapi/master/images/report-print-closed.png"
    width="700",
    alt="An overview screenshot of the report."
  >
  <img
    src="https://raw.githubusercontent.com/scanapi/scanapi/master/images/report-print-request.png"
    width="700"
    alt="A screenshot of the report showing the request details."
  >
  <img
    src="https://raw.githubusercontent.com/scanapi/scanapi/master/images/report-print-response.png"
    width="700",
    alt="A screenshot of the report showing the response and test details"
  >
</p>
```

The images are stored here: https://github.com/scanapi/scanapi/tree/main/images

Thank you once again!

**Comment by renato04** [comment]
@camilamaia It's done!

**Comment by renato04** [comment]
@camilamaia no problem.
I understood, I'm going to do that as soon as possible

**Comment by renato04** [comment]
@camilamaia It's done.
Let me know if is anything wrong.

**Comment by Pradhvan** [comment]
@renato04 just one minor change  can you squash the commits into one and add a structured commit message associated with it. 

You can follow the below commit template:

```
[Title]

[Body of the commit]

[Closes #issue number ]
```

Something like 👇🏾 
```
Updates README file with the new demo api version

* updates `name`, `path` with the new new demo API
* adds updated images

Closes #<issue number>
```

Feel free to let me know if you need any help with any of the steps.

**Comment by renato04** [comment]
Thank you @Pradhvan for the tip! 
Do I have to do that for this PR to be accepted?

**Comment by Pradhvan** [comment]
Hi @renato04 👋🏾 

>Do I have to do that for this PR to be accepted?
Yes, this would also be really help in improving standardising the GitHub workflow. 

Let me know if you need any help.

**Comment by renato04** [comment]
Hi @Pradhvan!
Is it good now?

**Comment by Pradhvan** [comment]
> Hi @Pradhvan!
> Is it good now?

The final commit looks good. You just need to squash all 4 commits into 1 commit now.

**Comment by renato04** [comment]
@Pradhvan what about now? 😆

**Pull request closed without merging**
