### PR TITLE
Fixed all flake8 errors

### LINKED ISSUE #293: Unused imports
In some files, there are imports that are unused. Can be found as F401 using flake8.

### PR DESCRIPTION
**Pull request by JRubics**
closes #293

### CODE REVIEW

**Review by kelvins — COMMENTED** [review]
Excellent PR @JRubics :clap:

I would suggest removing unused variables instead of using `noqa: F841` annotation, WDYT?

I also created an issue related to flake8 (https://github.com/scanapi/scanapi/issues/270) some time ago. Maybe in the future we could use flake8 code check on the git hook or CI to avoid merging PRs with PEP8 issues.

**Comment by JRubics** [comment]
@kelvins thank you for the review! :smile: 
I added "noqa: F841" because of the comment at the beginning of the file that says: # Available imports to be used dinamically in the API spec. @camilamaia please tell me if this is still in use, or I can delete that imports too? Scanapi works without them, but I just wanted to check.

@kelvins  I totally agree with you about flake8 code check, that is something I also thought will be great to add. I will add that feature as soon as possible. Thank you for the suggestion! :smile:

**Comment by kelvins** [comment]
According to the `flake8` [violation codes](https://flake8.pycqa.org/en/latest/user/error-codes.html), F481 is related to local variables assigned but not used (which you can see in the test cases).

The error code related to imports not used is F401. I think it is necessary to keep these imports because of the dynamically evaluation.

**Comment by JRubics** [comment]
Oh I'm sorry, my bad. noqa F841 fixed

**Review by kelvins — APPROVED** [review]
LGTM

**Comment by camilamaia** [comment]
> @kelvins thank you for the review! 😄
> I added "noqa: F841" because of the comment at the beginning of the file that says: # Available imports to be used dinamically in the API spec. @camilamaia please tell me if this is still in use, or I can delete that imports too? Scanapi works without them, but I just wanted to check.
> 
> @kelvins I totally agree with you about flake8 code check, that is something I also thought will be great to add. I will add that feature as soon as possible. Thank you for the suggestion! 😄

@JRubics we still use it. We need them If we want to use this imports inside a `${{ }}` expression.

For example:

```yaml
vars:
      today: ${{datetime.datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ')}}
```

And btw, great job, thank you very much for the PR! And thanks @kelvins for helping in the review!

**Review by camilamaia — APPROVED** [review]
👏👏👏

**Pull request merged**
