### PR TITLE
feat: change requests to httpx

### LINKED ISSUE #208: Change `requests` to `httpx`
Change requests to httpx https://github.com/encode/httpx

## Features

HTTPX builds on the well-established usability of `requests`, and gives you:

* A broadly [requests-compatible API](https://www.python-httpx.org/compatibility/).
* Standard synchronous interface, but with [async support if you need it](https://www.python-httpx.org/async/).
* HTTP/1.1 [and HTTP/2 support](https://www.python-httpx.org/http2/).
* Ability to make requests directly to [WSGI applications](https://www.python-httpx.org/advanced/#calling-into-python-web-apps) or [ASGI applications](https://www.python-httpx.org/async/#calling-into-python-web-apps).
* Strict timeouts everywhere.
* Fully type annotated.
* 99% test coverage.

Plus all the standard features of `requests`...

* International Domains and URLs
* Keep-Alive & Connection Pooling
* Sessions with Cookie Persistence
* Browser-style SSL Verification
* Basic/Digest Authentication
* Elegant Key/Value Cookies
* Automatic Decompression
* Automatic Content Decoding
* Unicode Response Bodies
* Multipart File Uploads
* HTTP(S) Proxy Support
* Connection Timeouts
* Streaming Downloads
* .netrc Support
* Chunked Requests

### PR DESCRIPTION
**Pull request by taconi**
## Description
Change requests to httpx

## Motivation behind this PR?
#208

## What type of change is this?
Feature

## Checklist
 

- [x]  I have added a changelog entry / my PR does not need a new changelog entry. [Instructions](https://github.com/scanapi/scanapi/wiki/Changelog).
- [x] I have added/updated unit tests. [Instructions](https://github.com/scanapi/scanapi/wiki/Writing-Tests).
- [x] New and existing unit tests pass locally with my changes. [Instructions](https://github.com/scanapi/scanapi/wiki/Run-ScanAPI-Locally#tests)
- [x] I have self-documented code my changes by adding docstring(s) and comment(s). [Instructions](https://github.com/scanapi/scanapi/wiki/First-Pull-Request#7-make-your-changes)
- [x] Current PR does not significantly decrease the code coverage and docstring coverage.
- [x] My code follows the style guidelines of this project.
- [x] I have run ScanAPI locally and manually tested my changes. [Instructions](https://github.com/scanapi/scanapi/wiki/Run-ScanAPI-Locally).
- [x] I have squashed my commits. [Instructions](https://github.com/scanapi/scanapi/wiki/Squashing-Commits).

## Issue

Closes #208

### CODE REVIEW

**Comment by taconi** [comment]
It needed to update the version of the poetry to 1.2.2 because there was an error that was corrected in this version, and the version of the python for 3.8.x because the flake8 was breaking (no further support for version 3.7)

**Comment by uesleicarvalhoo** [comment]
@camilamaia excluding conflicts, there are some reason to don't merge this?

**Comment by camilamaia** [comment]
@uesleicarvalhoo @taconi 
I was checking and there are still many downloads of ScanAPI with Python 3.7:
https://pypistats.org/packages/scanapi 

I also don't want to push to a breaking change "only" because of a development package. So I am not sure what would be the best way to go here...

This is the same thing that is blocking me here: https://github.com/scanapi/scanapi/pull/566 🤔 

Ideas?

**Comment by uesleicarvalhoo** [comment]
@camilamaia httpx is available for python 3.7 or higher, no? 🤔

**Comment by camilamaia** [comment]
@taconi I am fixing the pipelines and the dependencies. I will let you know as soon as I merge the changes :)

**Comment by taconi** [comment]
It's giving an error in the demo-api, but I cloned this project and ran it locally and it's working with the definition of the files ./examples/demo-api/scanapi.yaml and ./examples/demo-api/scanapi.conf

**Comment by camilamaia** [comment]
We can ignore the `ScanAPI Examples / Demo API` check. It is a problem with GitHub actions and not the code. Sorry for the inconvenience 😢 .

The other failing check is regarding this line: https://github.com/scanapi/scanapi/pull/557/files#diff-eac99bc2fbdb913fdf03fcd5f9b3cbd3583df042256d0ab1aa42a24421c621a6R172

image

What do you think of having more specific exceptions: https://www.python-httpx.org/exceptions/?
At least for these main four HTTPError, InvalidURL, CookieConflict, StreamError.

**Review by camilamaia — APPROVED** [review]
Thanks @taconi !!

**Pull request merged**
