### PR TITLE
Added a link to video tutorial about ScanApi and an image in the READ…

### PR DESCRIPTION
**Pull request by morvanabonin**
# Description

Added a link of the video tutorial about ScanApi and an image in the README file.

## Type of change
Just an update.

## How Has This Been Tested?
Confirm if the image is in the right place and the link was right.

### CODE REVIEW

**Review by marcuxyz — COMMENTED** [review]
its be ok!

**Comment by marcuxyz** [comment]
@morvanabonin can you write in changelog file your changes. to CI  to be pass.

Please try it https://github.com/scanapi/scanapi/wiki/Changelog

**Comment by camilamaia** [comment]
@marcuxyz this error on chagenlog github action happens when the repo is forked. Because the action has not the permission to access the data:

image

https://github.com/actions/first-interaction/issues/10. The issue is still opened 😞 

I will merge the PR since it is looks fine, ok @marcuxyz? Thank you and @morvanabonin 👌

**Review by camilamaia — APPROVED** [review]

**Comment by camilamaia** [comment]
Hey, @morvanabonin thank you very much for the PR!

Also, I am going to send you an invite to join the ScanAPI org on GitHub 🚀 We invite everyone that has contributed with a merged PR in any of our repos. Here you can check our [Community Continuity Guidelines](https://github.com/scanapi/contributors/blob/master/Contributing.md) so you can understand better how it works.

And once again, thank you! 🙇‍♀️

**Comment by marcuxyz** [comment]
> @marcuxyz this error on chagenlog github action happens when the repo is forked. Because the action has not the permission to access the data:
> 
> image
> 
> [actions/first-interaction#10](https://github.com/actions/first-interaction/issues/10). The issue is still opened 😞
> 
> I will merge the PR since it is looks fine, ok @marcuxyz? Thank you and @morvanabonin 👌

Thanks for this my friend

**Pull request merged**
