### PR TITLE
update gitignore

### PR DESCRIPTION
**Pull request by marcuxyz**
add follow lines:

```
scanapi-report.html
scanapi.yaml
```

### CODE REVIEW

**Review by camilamaia — APPROVED** [review]

**Comment by barbosa** [comment]
Hey @marcuxyz . Thanks for the PR. Would you mind explaining a bit the reasoning behind adding these to lines?

This could be tricky, given that this will match a [data test file](https://github.com/scanapi/scanapi/blob/master/tests/data/scanapi.yaml) and potentially other cases in the future if we want to have a more functional type of tests.

**Comment by camilamaia** [comment]
@barbosa great point. But I believe, since the test files are not in the root path, they wouldn't be ignored, right? So I believe we should be good if we store all the data files inside any other folder.

image

@marcuxyz correct me if I am wrong, but I believe the idea is to prevent adding files that we are using to manually test the lib locally.

**Comment by camilamaia** [comment]
@barbosa @marcuxyz, Hmmm but in fact for new files git will ignore them. Maybe it is indeed a good idea to revert this 🤔

**Comment by marcuxyz** [comment]
@barbosa we can ignore it, but whoever contributes to the project will have to be very careful when testing to not upload this file.

**Comment by barbosa** [comment]
Yeah, that's why I asked about the reasoning. Just to understand if this is a common thing or not when developing new features on ScanAPI. I usually consume these files from a different path (sample apps) so they're never inside this repo. But if this is something people are doing and I just don't have the context, we can consider the case. Or also make it explicit we intend to ignore only those in the root folder instead, which could be the most common case if what I said before applies.

**Comment by camilamaia** [comment]
@marcuxyz @barbosa I created an issue to re-add the lines https://github.com/scanapi/scanapi/issues/326. Also, I will add to the newcomers guide a line advising to consume these files from a different path. What do you think?

I believe it is more critical to not send the files to git (and waste sometime debugging to find the problem) than send the wrong ones. Besides, in the PR we can check if a file was sent by mistake.

**Pull request merged**
