### PR TITLE
feat: implement option key (#529)

### LINKED ISSUE #529: There are some option to set verify=False to requests?
### Environment
- Operating System: Linux Xubuntu 16.04
- Python version: 3.6

### What you intend to do with scanapi ?
A  want make a request to web server running locally with HTTPS enabled, but I need some way to make requests dont verify SSL.

I need something like that?
requests.post(url='https://example.com', data={'bar':'baz'}, verify=False)

### Expected behavior ?

There are some option for me reach that, saying to requests include 'verify=False'?

I'm trying to avoid this error:

Error to make request `https://127.0.0.1:443/auth/authenticate`. 
HTTPSConnectionPool(host='127.0.0.1', port=443): Max retries exceeded with url: /auth/authenticate (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)'),))

Thanks in advance!

---

scanapi has a [discord server](https://discord.gg/f3cCXJ2ZPB) so feel free to join and say 👋 hello. Maybe share the issue link?

### PR DESCRIPTION
**Pull request by uesleicarvalhoo**
## Description
Implement key `options` to `request` and `endpoint` nodes for allow keywords in to `request` performing call.
The avaliable keys are `timeout` and `verify`. If both has same `options`, `request node` is priorized.

## Motivation behind this PR?
#529

## What type of change is this?
Feature

## Checklist
 

- [x]  I have added a changelog entry / my PR does not need a new changelog entry. [Instructions](https://github.com/scanapi/scanapi/wiki/Changelog).
- [x] I have added/updated unit tests. [Instructions](https://github.com/scanapi/scanapi/wiki/Writing-Tests).
- [x] New and existing unit tests pass locally with my changes. [Instructions](https://github.com/scanapi/scanapi/wiki/Run-ScanAPI-Locally#tests)
- [x] I have self-documented code my changes by adding docstring(s) and comment(s). [Instructions](https://github.com/scanapi/scanapi/wiki/First-Pull-Request#7-make-your-changes)
- [x] Current PR does not significantly decrease the code coverage and docstring coverage.
- [x] My code follows the style guidelines of this project.
- [x] I have run ScanAPI locally and manually tested my changes. [Instructions](https://github.com/scanapi/scanapi/wiki/Run-ScanAPI-Locally).
- [x] I have squashed my commits. [Instructions](https://github.com/scanapi/scanapi/wiki/Squashing-Commits).

## Issue

Closes #529

### CODE REVIEW

**Comment by Pradhvan** [comment]
@uesleicarvalhoo thanks for the PR ⭐ 

Two of the checks that are failing are:

1. Changelog Reminder / Changelog Reminder (pull_request) 
  * Since it's a new feature can you please add a change log to a changelog. Add an entry to [CHANGELOG.md](https://github.com/scanapi/scanapi/blob/main/CHANGELOG.md) in your branch. That should fix this check.

2.  ScanAPI Examples / poke-api (pull_request)
```
 [FAILED] pokeapi::pokemon::list_all::response_time_is_under_half_second
          response.elapsed.total_seconds() < 0.5 is false
```
This is the test that is failing that requires GET call to [pokeapi](https://pokeapi.co/api/v2/pokemon) to be under 0.5 sec. @camilamaia can this be due a flaky tests ?

**Comment by Pradhvan** [comment]
@astenstrasser @camilamaia the changes looks good to me. What do you folks think ?

**Comment by uesleicarvalhoo** [comment]
Hi @camilamaia, thanks! 😁

I thought that all requests is to same serve, then was no sense enalbe verify to one and disable to another one, but maybe some scenarios it makes sense, i will be update it!

**Review by camilamaia — APPROVED** [review]

**Comment by camilamaia** [comment]
@uesleicarvalhoo Congrats on your first merged PR! 🌟 Thank you very much!

I am going to send you an invite to join the ScanAPI org on GitHub 🚀 We invite everyone that has contributed with a merged PR in any of our repositories. Here you can check our [Contributing Guidelines](https://github.com/scanapi/contributors/blob/main/CONTRIBUTING.md) so you can understand better how it works.

Check your email/GitHub notifications to find the invite. If you accept it, you will also be able to clone directly our repositories, without needing to fork them. 

Welcome on board and once again, thank you! 🙇‍♀️

**Pull request merged**
