### PR TITLE
Fixed hide_response body (#370)

### LINKED ISSUE #370: Fix `hide_response` `body`
## Description

```shell
Error to make request `http://demo.scanapi.dev/health/`.
'Response' object has no attribute 'body'
```

We need to check if http_message has body attribute before accessing it: https://github.com/scanapi/scanapi/blob/master/scanapi/hide_utils.py#L66

request.body exists, but response.body doesn't. For response we need to use response.text or response.content

## Reproducing the error

Spec File:
```yaml
# scanapi.yaml

endpoints:
  - name: snippets-api
    path: ${BASE_URL}
    headers:
      Content-Type: application/json
    requests:
      - name: health
        method: get
        path: /health/
        tests:
          - name: status_code_is_200
            assert: ${{ response.status_code == 200 }}
          - name: bode_equals_ok
            assert: ${{ response.json() == "OK!" }}
      - name: get_token
        path: /api-token-auth/
        method: post
        body:
            username: ${USER}
            password: ${PASSWORD}
        vars:
          token: ${{response.json()["token"]}}
        tests:
          - name: status_code_is_200
            assert: ${{ response.status_code == 200 }}
```

Configuration File
```yaml
# scanapi.conf
project_name: Snippets API
report:
  hide_response:
    body:
      - token
```

```shell
$ scanapi run
Loading file ./scanapi.conf
Loading file scanapi.yaml
Writing documentation
Making request GET http://demo.scanapi.dev/health/

Error to make request `http://demo.scanapi.dev/health/`.
'Response' object has no attribute 'body'
...
```

image

### LINKED ISSUE #371: Hide response content sensitive info
## Description

Hide response content sensitive info. 

Since body does not exist for responses objects (see [this](https://github.com/scanapi/scanapi/issues/370) for more details), we need a config to hide content fields for a response

```yaml
report:
  hide-response:
    headers:
      - Authorization
    content:
      - token
```

### PR DESCRIPTION
**Pull request by hebertjulio**
Closes #370 
Closes #371

### CODE REVIEW

**Review by camilamaia — COMMENTED** [review]
Hey, @hebertjulio, would you mind creating new tests for the changes you've made? I've just created a detailed doc of how to do it:

- https://github.com/scanapi/scanapi/wiki/First-Pull-Request#8-test-your-changes
- https://github.com/scanapi/scanapi/wiki/Writing-Tests

Please, let me know if you need any help!

**Comment by hebertjulio** [comment]
Of course @camilamaia  I can do it, but I don't know which test can be created, at the moment I am learning to create tests, and I have difficulties in defining the tests that need to be created.

**Comment by camilamaia** [comment]
> Of course @camilamaia I can do it, but I don't know which test can be created, at the moment I am learning to create tests, and I have difficulties in defining the tests that need to be created.

No problem, I can help you :) I would create:
- one test to check that it uses `.body` when there is a body. And it overrides the body information.
- one test to check that it uses `.content` when the body is empty. And it hides the content information.
- one test to check the code does not break when there is no `.body` nor `.content`.

This is the file https://github.com/scanapi/scanapi/blob/master/tests/unit/test_hide_utils.py where you should add the tests.

Let me know how it goes!

**Comment by hebertjulio** [comment]
Hi @camilamaia, i don't understand why there are two gets method in line 8 of test_hide_utils.py file. is that correct?

https://github.com/scanapi/scanapi/blob/4ee9c9b20608ab218b3648f040dad58387bdc676/tests/unit/test_hide_utils.py#L8

**Comment by camilamaia** [comment]
@hebertjulio yes, this is **mocking** the `requests.get` function! Let me try to give you an overview about it.

Unit tests don't call external services, external APIs. Unit tests must test only the `unit`. In other words, they should test only the **method** itself. Unit tests should not test anything external to the method. Not any other method that is called inside, any other class, any other service.

Ok, but what if the method I am testing calls an external API? What should I do? Here is where the `mock` enters! You mock the external call. Wait, what? 

Yes, let's say your method calls 

```python
def my_method:
   requests.get("http://test.com")
```

with mock, we say: 

> hey, method, every time you would call this line `requests_mock.get("http://test.com")`, now you will use my mock instead!

```python
requests_mock.get("http://test.com", text="data")
return requests.get("http://test.com")
```

So, instead of the code try to real do a GET request to `http://test.com`, it will use the mock. It will always receive a Fake Response object where the text attribute of it will be `data`.

It is a bit complex in the beginning to understand `mock`. Maybe these docs can help you

https://requests-mock.readthedocs.io/en/latest/pytest.html#pytest
https://realpython.com/python-mock-library/
https://blog.onedaytesting.com.br/test-doubles/

**Comment by hebertjulio** [comment]
@camilamaia creating the tests I found what can be a problem when the sensitive data of a body is overwritten, following the implemented logic, when I don't have the body attribute, I have to work with the content attribute, but this field cannot be overwritten as well as the body attribute. I believe that the overwritten has to occur in the printing of the report and not as an intermediate process.

https://github.com/scanapi/scanapi/blob/4ee9c9b20608ab218b3648f040dad58387bdc676/scanapi/hide_utils.py#L65-L69

**Comment by camilamaia** [comment]
@hebertjulio indeed. But in the earlier versions of requests, you can set the attribute `_content` now, and it should work!

```python
http_msg._content = json.dumps(body).encode("utf-8")
```

https://stackoverflow.com/a/26342225/8298081

**Pull request merged**
