### PR TITLE
Adding support to head and options methods

### PR DESCRIPTION
**Pull request by rvmoura96**
Closes https://github.com/scanapi/scanapi/issues/349

### CODE REVIEW

**Comment by marcuxyz** [comment]
@camilamaia would cool, to integrate the `pr` #347 for resolve the lint problem.

**Comment by camilamaia** [comment]
@marcuxyz done!! ✅ @rvmoura96 you can pull from the master to fix it :)

**Comment by rvmoura96** [comment]
Oh thanks @camilamaia  and @marcuxyz , i'll be updating with master

**Comment by camilamaia** [comment]
@rvmoura96 cool, now you can run `make format` to fix the lint.

**Comment by rvmoura96** [comment]
i think now it's all good @marcuxyz and @camilamaia

**Review by camilamaia — APPROVED** [review]

**Pull request merged**
