### PR TITLE
Render JSON content with indentation

### PR DESCRIPTION
**Pull request by abreumatheus**
### Added
- JSON response is now properly rendered, instead of plain text;

### CODE REVIEW

**Comment by abreumatheus** [comment]
Just as observation: I used a javascript library to render the json in a "interactive" way, but if the user disables javascript on the browser (or for some reason the browser or device doesn't support javascript) it won't break the report, it will just fall back to plain text.

**Comment by barbosa** [comment]
Nice! Do you have a screenshot of how that's being rendered, @abreumatheus ?

**Comment by abreumatheus** [comment]
> Nice! Do you have a screenshot of how that's being rendered, @abreumatheus ?

Sure do!

json_render

**Comment by camilamaia** [comment]
@abreumatheus hi! I tested it here for the PokèAPI and it worked perfectly, beautiful! ⭐ Super cool feature collapsing indeed, I love it. It worked for firefox, chrome and safari 👏 

But when I tested for the `demo-api`, it did not work quite well. Would you mind to try it with demo-api too?

https://github.com/scanapi/scanapi/blob/master/CONTRIBUTING.md#clone-scanapi-examples

```shell
$ source ../examples/demo-api/.env
$ poetry run scanapi ../examples/demo-api/api.yaml -c ../examples/demo-api/.scanapi.yaml -o ../examples/demo-api/scanapi-report.html
```

image

---

image

---

image

I don't know if it is a problem with our demo-api... 🤷‍♀️

**Comment by abreumatheus** [comment]
@camilamaia I will check it here and see if there is anything wrong with both :)

**Comment by abreumatheus** [comment]
@camilamaia The problem is actually with the demo api not outputing valid JSON in some endpoints, like the first one where the response is `OK!` in plain text instead of something like `{"msg": "OK!"}`. And if one of them is broken, the rest won't render.

**Comment by abreumatheus** [comment]
@camilamaia @barbosa Hi guys! Just updated the script, and now it's non blocking. If it encounters non valid JSON it just goes to the next response. Could you test it again with the demo api?

**Comment by camilamaia** [comment]
@abreumatheus it worked perfectly! Ty very much!. This is feature is really important

**Pull request merged**
